apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: azure-cli-cronjob
  namespace: <your-namespace>
spec:
  schedule: "*/30 * * * *"  # Every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: azure-cli
              image: mcr.microsoft.com/azure-cli
              command:
                - /bin/sh
                - -c
                - >
                  az login --service-principal -u <client-id> -p <client-secret> --tenant <tenant-id> && 
                  az account get-access-token --resource=https://dev.azure.com --query accessToken -o tsv |
                  oc patch secret azuredevops-token -n <your-namespace> --type=json -p='[{"op": "replace", "path": "/data/access-token", "value":"'"$(echo -n $(cat -) | base64)"'"}]'
          restartPolicy: OnFailure
