apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: azure-cli-cronjob
  namespace: <your-namespace>
spec:
  schedule: "*/30 * * * *"  # Every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: azure-cli
              image: mcr.microsoft.com/azure-cli
              command:
                - /bin/sh
                - -c
                - >
                  # Add your commands to run inside the container here
                  echo "Running Azure CLI tasks"
          restartPolicy: OnFailure
